config/routes.rb
Rails.application.routes.draw do
  resources :books
  root to: 'homes#top'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    validates :title, presence: true
    validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @books = Book.all
    @book = Book.new
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end
  
  def update
    @book = Book.find(params[:id])
   if @book.update(book_params)
     redirect_to book_path(@book.id), notice: "Book was successfully updated."
   else
     render :edit
   end
  end
  
  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end
  
  def new
    @book = Book.new
  end
  
  def create
    @book = Book.new(book_params) 
    @books = Book.all
   if @book.save
     redirect_to book_path(@book.id), notice: "Book was successfully created"
   else
     render :index
   end
  end
  
  private
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
    def top
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/books/edit.html.erb
<h1>Editing Book</h1>
 <% if @book.errors.any? %>
  <%= @book.errors.count %> error
  <% @book.errors.full_messages.each do |message| %>
   <%= message %>
  <% end %>
 <% end %>
<%= form_with model:@book, url:"/books/#{@book.id}", local:true do |f| %>
<div class="field">
 <label for="book_title">Title</label>
 <%= f.text_field :title %>
</div>

<div class="field">
 <label for="book_body">Body</label>
 <%= f.text_area :body %>
</div>
 <%= f.submit 'Update Book' %>
<% end %>
<%= link_to 'Show', book_path(@book.id) %>
 |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<body>
 <h1>Books</h1>
 
 <table dis>
  
  <thead>
   <tr>
    <th>Title</th>
    <th>Body</th>
    <th colspan="3"></th>
   </tr>
  </thead>
  
  <tbody>

   <% @books.each do |book| %>
    <tr>
     <td><%= book.title %></td>
     <td><%= book.body %></td>
     <td><%= link_to 'show', book_path(book.id) %></td>
     <td><%= link_to 'Edit', edit_book_path(book.id) %></td>
     <td><%= link_to 'Destroy', book_path(book.id), method: :delete, "data-confirm" => "Are you sure?" %></td>
    </tr>
   <% end %>
   
  </tbody>
 </table>
 
 <h2>New book</h2>

 <% if @book.errors.any? %>
  <%= @book.errors.count %> error
  <% @book.errors.full_messages.each do |message| %>
   <%= message %>
  <% end %>
 <% end %>
 
<%= form_with model:@book, local:true do |f| %>
  <div class="field">
   <label for="book_title">title</label>
   <%= f.text_field :title %>
  </div>
  
  <div class="field">
   <label for="book_body">body</label>
   <%= f.text_area :body %>
  </div>
  
  
  <%= f.submit 'Create Book' %>
 <% end %>
</body>

app/views/books/new.html.erb
<h1>topページ</h1>

app/views/books/show.html.erb
<% if flash[:notice] %>
  <p><%= flash[:notice] %></p>
<% end %>
<p>
 <strong>Title:</strong>
 <%= @book.title %>
</p>

<p>
 <strong>Body:</strong>
 <%= @book.body %>
</p>

<%= link_to 'Edit', edit_book_path(@book.id) %>
|
<%= link_to 'Back', books_path %>

app/views/homes/top.html.erb
<h1>ようこそ
<strong>Bookers</strong>
へ!
</h1>

<p>
    <strong>Bookers</strong>では、さまざまな書籍に関するあなたの意見や</p>
    <p>印象を共有し交換することができます</p>
<p>
    <%= link_to "start", books_path %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>